<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body {
            text-align:center;
        }
    .modify {
      border:1px solid black;
      
      text-align:center;
      display: inline-block;
      background-color: beige;
    }
    </style>
</head>
<body>
    <h1>Add new stamp</h1>

    <form action ="/home/submit" method="post" class="modify" enctype="multipart/form-data">
        <label>Year :</label><br><input type="number" name = "year"><br>
        <label>Picture :</label><br><input type="file" name = "picture"><br>
        <label>Name :</label><br><input type="text" name = "name"><br>
        <label>Description :</label><br><input type="text" name = "description"><br>
        <label>Collection :</label><br><input type="text" name = "collection"><br>
        <label>Width :</label><br><input type="number" name = "width"><br>
        <label>Heigth :</label><br><input type="number" name = "heigth"><br>

        <input type="submit" name = "submit" value = "submit">
    </form>
</body>
</html>